const state = () => ({
  active: "en" as "en" | "cn",
  text: text.en as Object
});

const mutations = {
  setLanguage(state: any, language: "en" | "cn") {
    state.active = language;
    state.text = text[language];
  },

  changeLanguage(state: any) {
    let lang = "en";
    if (state.active === "en") {
      lang = "cn";
    }
    state.active = lang;
    state.text = text[lang as "en" | "cn"];
  }
};

const actions = {};

export default {
  namespaced: true,
  state,
  mutations,
  actions
};

const text = {
  en: {
    navbar: {
      logo: "QuantumGo",
      lang: "Language",
      leaderboard: "Leaderboard",
      lobby: "Lobby",
      recent: "Recent",
      share: "Share",
      share_website: "Click on the link to experience online quantum Go battles: ",
      share_battle: "Click on the link to play quantum Go with me now: ",
      copy_success: "Already copied to clipboard.",
      login: "Login",     
      mute_all: "Mute all",
      unmute_all: "Unmute all",
      sfx: "Move",
      bgm: "BGM"
    },
    common: {
      login_required: "Log in to continue.",
      waiting: "Waiting",
      opponent: "Opponent",
      owner: "Owner",
      you: "You"
    },
    board: {
      put_chess_error: "No playing chess here",
      ws_connection_error: "Game connection error",
      review_cannot_play: "Can't play moves while viewing previous round.",
      removal_cannot_play: "Can't play during stone removal."
    },
    index: {
      title: "Play Go Online",
      desc: "Experience the fusion of ancient strategy and modern intelligence. Play against Al, learn the beauty of Go, and train your mind with every move.",
      create: "Create Room",
      join: "Join Room",
      btn_start: "Start Game",
      create_room_error: "Failed to create room",
      create_room_error_empty_options: "Please select game mode and board size",
      create_room_title: "Create Room",
      game_mode_title: "Game Mode",
      game_mode_placeholder: "Please select game mode",
      game_mode_pvp: "Player vs Player",
      game_mode_ai: "Player vs AI",
      model_title: "Model",
      model_placeholder: "Please select chessboard model",
      model_7: "7x7",
      model_9: "9x9",
      model_13: "13x13",
      model_19: "19x19",

      // Time control (UI only; disabled logic)
      tc_title: "Time Control",
      tc_placeholder: "Select time control",
      tc_unlimited: "Unlimited",
      tc_absolute: "Absolute",
      tc_simple: "Simple",
      tc_fischer: "Fischer",
      tc_byoyomi: "Byo-Yomi",
      tc_main_time: "Main Time (min)",
      tc_increment: "Increment (sec)",
      tc_max_cap: "Max Cap (min, 0=none)",
      tc_period_time: "Period Time (sec)",
      tc_periods: "Periods (count)",
      tc_stones_per_period: "Stones / Period",
      cancel: "Cancel",
      confirm: "Confirm"
    },
    room: {
      pass: "Pass",
      draw: "Draw",
      takeback: "Takeback",
      resign: "Resign",
      chat_placeholder: "Type here to chat, press Enter to send.",
      ws_disconnected: "Game server disconnected.",
      not_round: "It's not your turn now.",
      pass_early: "Pass is not allowed in the first two moves.",
      winner: "The game is over, and you have won!",
      loser: "The game is over, and the opponent has the upper hand.",
      finish_title: "Finish",
      side_black: "Black",
      side_white: "White",
      game_over_side_win: "Game over, {side} wins",
      ai_pass: "AI pass",
      opponent_pass: "Opponent passed",
      position_occupied: "This position is already occupied",
      invalid_move: "Cannot play at this position",
      takeback_too_few: "Too few moves to take back",
      takeback_success: "Takeback successful",
      pass_too_few: "Too few moves to pass",
      resign_confirm: "Are you sure you want to resign?",
      ai_resign_you_win: "AI resigns, you win",
      ai_win: "Game over, AI wins",
      moves: "Moves",
      points: "Capture",
      score: "Score",
      score_estimator: "Score Estimator",
      hide_estimate: "Hide Estimate",
      end_game: "End Game",
      estimating: "Estimating...",
      estimate_failed: "Estimate failed",
      start_game: "Start Game!",
      time_up: "Operation timeout, pass this round",
      back_apply_waiting: "The application has been submitted and is awaiting the other party's action.",
      back_apply_early: "The first two moves are not allowed to take back.",
      back_apply_title: "Takeback Request",
      back_apply_content: "The opponent has requested a takeback. Do you agree?",
      back_apply_btn_agree: "Agree",
      back_apply_btn_reject: "Reject",
      back_apply_success: "The other party has agreed to your application.",
      back_apply_fail: "The other party has rejected your application.",
      stone_removal_title: "Stone Removal",
      continue_game: "Continue",
      auto_score: "Auto-score",
      clear: "Clear", 
      accept: "Accept",
      accept_confirmed: "Accept ✓",
      opponent_accepted: "Opponent accepted",
      opponent_pending: "Opponent pending",
      continue_game_success: "Continue game",
      opponent_continue_game: "Opponent chose to continue game",
      board1: "Board1",
      board2: "Board2", 
      winrate: "Winrate",
      score_lead: "Score Lead",
      score_detail: "Score Detail",
      area: "Area",
      komi: "Komi",
      total: "Total",
      result: "Result",
      close: "Close"
    },
    join: {
      net_error: "Network error, please check your network connection.",
      room_not_found: "Room not found, please check the room ID.",
      room_playing: "The game is currently underway.",
      room_finished: "The game has already finished.",
      join_self: "You cannot join your own room."
    },
    leaderboard: {
      title: "Player Leaderboard",
      subtitle: "View your ranking among Quantum Go players",
      rank: "Rank",
      username: "Username",
      rating: "Rating",
      rd: "RD",
      games: "Games",
      win_rate: "Win Rate",
      total_players: "Total Players",
      avg_rating: "Average Rating",
      no_data: "No players found for this board size"
    },
    lobby: {
      title: "Lobby",
      filter_board: "Board",
      filter_all: "All",
      btn_refresh: "Refresh",
      loading: "Loading rooms...",
      empty: "No rooms found",
      host: "Host",
      status: "Status",
      status_waiting: "Waiting",
      status_playing: "Playing",
      status_finished: "Finished",
      model: "Model",
      created: "Created",
      btn_join: "Join"
    },
    recent: {
      title: "Recent Games",
      all: "All",
      waiting: "Waiting",
      playing: "Playing",
      finished: "Finished",
      refresh: "Refresh",
      loading: "Loading...",
      empty: "No recent games",
      opponent: "Opponent",
      status: "Status",
      model: "Board",
      updated: "Updated",
      continue: "Continue",
      review: "Review"
    },
    login: {
      title_login: "Login",
      title_register: "Register",
      label_name: "Username",
      label_password: "Password",
      label_password_confirm: "Confirm Password",
      placeholder_name: "Please enter your username",
      placeholder_password: "Please enter your password",
      placeholder_password_confirm: "Please confirm your password",
      btn_login: "Login now",
      btn_register: "Register now",
      password_not_confirm: "The two passwords do not match",
      login_error: "Login failed, please check your username and password",
      login_success: "Welcome: ",
      register_error: "Registration failed, please check your username"
    }
  },
  cn: {
    navbar: {
      logo: "量子围棋",
      lang: "语言",
      leaderboard: "排行榜",
      lobby: "大厅",
      recent: "最近",
      share: "分享",
      share_website: "点击链接体验在线量子围棋：",
      share_battle: "点击链接与我对弈量子围棋：",
      copy_success: "已复制到剪贴板",
      login: "登录",
      mute_all: "全部静音",
      unmute_all: "取消静音",
      sfx: "落子音效",
      bgm: "背景音乐"
    },
    common: {
      login_required: "需要登录后继续。",
      waiting: "等待中",
      opponent: "对手",
      owner: "房主",
      you: "你"
       },   
      
    board: {
      put_chess_error: "此处不能落子",
      ws_connection_error: "游戏服务器连接错误",
      review_cannot_play: "回顾模式下无法落子",
      removal_cannot_play: "数子阶段无法落子"
    },
    index: {
      title: "在线对弈",
      desc: "体验古老策略与现代智能的融合。与 AI 或玩家对弈。",
      create: "创建房间",
      join: "加入房间",
      btn_start: "开始游戏",
      create_room_error: "创建房间失败",
      
      create_room_error_empty_options: "请选择模式、棋盘大小和倒计时",
      // 时间设置（仅展示，逻辑已禁用）
      tc_title: "时控",
      tc_placeholder: "请选择时控类型",
      tc_unlimited: "不限时",
      tc_absolute: "绝对用时",
      tc_simple: "简单用时",
      tc_fischer: "费舍尔",
      tc_byoyomi: "日本读秒",
      tc_main_time: "基本时间（分钟）",
      tc_increment: "每步增时（秒）",
      tc_max_cap: "最多累积（分钟，0为不限制）",
      tc_period_time: "每读秒（秒）",
      tc_periods: "读秒次数",
      tc_stones_per_period: "每读秒手数",

      create_room_title: "创建房间",
      game_mode_title: "对局模式",
      game_mode_placeholder: "请选择模式",
      game_mode_pvp: "玩家对战",
      game_mode_ai: "人机对战",
      model_title: "棋盘",
      model_placeholder: "请选择棋盘大小",
      model_7: "7x7",
      model_9: "9x9",
      model_13: "13x13",
      model_19: "19x19",
      countdown_title: "倒计时",
      countdown_placeholder: "请选择回合时间",
      countdown_unlimited: "不限时",
      cancel: "取消",
      confirm: "确定"
    },
    room: {
      pass: "停着",
      draw: "和棋",
      takeback: "悔棋",
      resign: "认输",
      chat_placeholder: "在此输入消息，回车发送",
      ws_disconnected: "服务器连接已断开",
      not_round: "现在不是你的回合",
      pass_early: "前两手不能停着",
      winner: "对局结束，你赢了！",
      loser: "对局结束，你输了",
      finish_title: "结束",
      side_black: "黑方",
      side_white: "白方",
      game_over_side_win: "对局结束，{side} 胜",
      ai_pass: "AI 停着",
      opponent_pass: "对手停着",
      position_occupied: "此处已有棋子",
      invalid_move: "该位置不可落子",
      takeback_too_few: "步数过少，无法悔棋",
      takeback_success: "悔棋成功",
      pass_too_few: "步数过少，无法停着",
      resign_confirm: "确认要认输吗？",
      ai_resign_you_win: "AI 认输，你赢了",
      ai_win: "对局结束，AI 获胜",
      moves: "手数",
      points: "提子",
      score: "得分",
      score_estimator: "形势判断",
      hide_estimate: "隐藏估算",
      end_game: "结束游戏",
      estimating: "计算中...",
      estimate_failed: "估算失败",
      start_game: "开始对局！",
      time_up: "超时，自动停着",
      back_apply_waiting: "已发送悔棋请求，等待对方处理",
      back_apply_early: "前两手不能悔棋",
      back_apply_title: "悔棋请求",
      back_apply_content: "对方请求悔棋，是否同意？",
      back_apply_btn_agree: "同意",
      back_apply_btn_reject: "拒绝",
      back_apply_success: "对方已同意你的请求",
      back_apply_fail: "对方拒绝了你的请求",
      stone_removal_title: "终局计算",
      continue_game: "继续游戏",
      auto_score: "自动计算",
      clear: "清空", 
      accept: "接受",
      accept_confirmed: "已接受 ✓",
      opponent_accepted: "对方已接受",
      opponent_pending: "等待对方",
      continue_game_success: "继续游戏",
      opponent_continue_game: "对方选择继续游戏",
      board1: "棋盘1",
      board2: "棋盘2",
      winrate: "胜率",
      score_lead: "得分优势",
      score_detail: "分数详情",
      area: "领地",
      komi: "贴目",
      total: "总计",
      result: "结果",
      close: "关闭"
    },
    join: {
      net_error: "网络错误，请检查网络连接",
      room_not_found: "未找到房间，请检查房间号",
      room_playing: "该房间正在对局中",
      room_finished: "该房间已结束",
      join_self: "不能加入自己创建的房间"
    },
    leaderboard: {
      title: "玩家排行榜",
      subtitle: "查看你的排名",
      rank: "排名",
      username: "用户名",
      rating: "等级分",
      rd: "RD",
      games: "对局数",
      win_rate: "胜率",
      total_players: "总玩家数",
      avg_rating: "平均等级分",
      no_data: "暂无数据"
    },
    lobby: {
      title: "大厅",
      filter_board: "棋盘",
      filter_all: "全部",
      btn_refresh: "刷新",
      loading: "加载房间中...",
      empty: "暂无房间",
      host: "房主",
      status: "状态",
      status_waiting: "等待中",
      status_playing: "对局中",
      status_finished: "已结束",
      model: "棋盘",
      created: "创建时间",
      btn_join: "加入"
    },
    recent: {
      title: "最近对局",
      all: "全部",
      waiting: "等待中",
      playing: "对局中",
      finished: "已结束",
      refresh: "刷新",
      loading: "加载中...",
      empty: "没有最近对局",
      opponent: "对手",
      status: "状态",
      model: "棋盘",
      updated: "更新于",
      continue: "继续",
      review: "复盘"
    },
    login: {
      title_login: "登录",
      title_register: "注册",
      label_name: "用户名",
      label_password: "密码",
      label_password_confirm: "确认密码",
      placeholder_name: "请输入用户名",
      placeholder_password: "请输入密码",
      placeholder_password_confirm: "请再次输入密码",
      btn_login: "立即登录",
      btn_register: "立即注册",
      password_not_confirm: "两次输入的密码不一致",
      login_error: "登录失败，请检查用户名与密码",
      login_success: "欢迎：",
      register_error: "注册失败，请检查用户名"
    }
  }
};




