[build]
builder = "nixpacks"

[deploy]
startCommand = "quantum-go-api"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
RUST_LOG = "info"
JWT_SECRET = "sGWfcMcDM1cMgsY4y9rsiA=="
